spring:
  application:
    name: "department-service"
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
server:
  error:
    include-stacktrace: never
  port: 8096

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka