spring:
  application:
    name: "department-service"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: dochero_department_db
  datasource:
    url: jdbc:postgresql://103.142.137.207:12345/dochero_department_db
    username: root
    password: 123456
    driverClassName: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://103.142.137.207:12345/dochero_department_db
    schemas: dochero_department_db
    user: root
    password: 123456
    locations: classpath:db/migration

server:
  error:
    include-stacktrace: never
  port: 8096

document-revision-service:
  url: http://103.48.192.223:40005

eureka:
  client:
    service-url:
      defaultZone: http://45.119.85.106:40000/eureka